#!/bin/sh

#{{ added by FriendlyELEC
. /etc/fa-boardinfo.sh
case ${BOARD} in
nanopi-r*)
    echo "$0: skiped."
    exit 1
    ;;
*)
    printf " "
    ;;
esac
#}}

# remove drm-logo
echo 1 > /sys/devices/platform/display-subsystem/graphics/fb0/blank
# create a always connected HDMI
echo on > /sys/class/drm/card0-HDMI-A-1/status
